name: Development

on:
  workflow_call:
    inputs:
      aws-account-id:
        required: true
        type: string
      application-name:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
  ENVIRONMENT: ${{ inputs.environment }}
  ECR_REPOSITORY: ${{ inputs.application-name }}-${{ inputs.environment }}

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-${{ inputs.environment }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        id: docker
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

#      - name: Deploy Amazon EC2 machines
#        with:
#          environment-variables: |
#            ENVIRONMENT=${{ env.ENVIRONMENT }}
#          image: ${{ steps.docker.outputs.image }}
