name: Development

on:
  workflow_call:
    inputs:
      aws-account-id:
        required: true
        type: string
      application-name:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
  ENVIRONMENT: ${{ inputs.environment }}
  ECR_REPOSITORY: ${{ inputs.application-name }}-${{ inputs.environment }}

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-${{ inputs.environment }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        id: docker
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-arg AWS_ELASTICACHE_REDIS_ENDPOINT=${{ secrets.AWS_ELASTICACHE_REDIS_ENDPOINT }} \
          --build-arg AWS_ELASTICACHE_REDIS_WITH_SSL=true \
          --build-arg ENVIRONMENT=${{ inputs.environment }} \
          --build-arg POSTGRESQL_PASSWORD='${{ secrets.POSTGRESQL_PASSWORD }}' \
          --build-arg POSTGRESQL_URL=${{ secrets.POSTGRESQL_URL }} \
          --build-arg POSTGRESQL_USERNAME=${{ secrets.POSTGRESQL_USERNAME }} .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update EC2 instances
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --filters "Name=tag:Category,Values=application" "Name=tag:Name,Values=java-app-instance*" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)
          
          IMAGE_URI="${{ steps.docker.outputs.image }}"
          
          echo "${{ secrets.EC2_SSH_KEY_PEM }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          
          for INSTANCE_ID in "${INSTANCE_IDS[@]}"; do
            echo "Updating instance $INSTANCE_ID..."
            ssh -o StrictHostKeyChecking=no -i "ec2_key.pem" ec2-user@$INSTANCE_ID << 'EOF'
              ./setup.sh
              docker pull $IMAGE_URI
              docker stop address_api || true
              docker rm address_api || true
              docker run --name address_api -d -p 8080:8080 $IMAGE_URI
            EOF
          done
          
          # Clean up the temporary PEM file
          rm ec2_key.pem
